// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ivanovaleksey/lendo/pkg/models"
)

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// ApplicationStatusChanged provides a mock function with given fields: ctx, change
func (_m *Notifier) ApplicationStatusChanged(ctx context.Context, change models.StatusChange) error {
	ret := _m.Called(ctx, change)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.StatusChange) error); ok {
		r0 = rf(ctx, change)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
