apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  LENDO_ADDR: :8000
  LENDO_DB_URL: postgres://lendouser:lendopass@postgres/api?sslmode=disable
  LENDO_NATS_URL: nats://nats:4222
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 8010
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ramone/lendo-api:v0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
