apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
spec:
  selector:
    matchLabels:
      app: bank
  replicas: 1
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: lendoab/interview-service:stable
          ports:
            - containerPort: 8000
