apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  labels:
    app: registry
data:
  LENDO_BANK_URL: http://bank:8000
  LENDO_DB_URL: postgres://lendouser:lendopass@postgres/registry?sslmode=disable
  LENDO_NATS_URL: nats://nats:4222
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - port: 8010
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: ramone/lendo-registry:v0.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: registry-config
